OnionArcitectureProject.Web/Areas/Admin/Controllers/SettingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using OnionArcitectureProject.Entities;
using OnionArcitectureProject.ViewModels;

namespace OnionArcitectureProject.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin , SuperAdmin")]
    public class SettingController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IPasswordHasher<ApplicationUser> _passwordHasher;

        public SettingController(UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
            IPasswordHasher<ApplicationUser> passwordHasher)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _passwordHasher = passwordHasher;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ListUserAsync()
        {
            var users = _userManager.Users.ToList();
            List<UserViewModel> usersInfo = new List<UserViewModel>();
            foreach (var user in users)
            {
                usersInfo.Add(new UserViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    UserName = user.UserName,
                    Roles = await _userManager.GetRolesAsync(user)
                });
            }
            return View(usersInfo);
        }



        [HttpGet]
        public async Task<IActionResult> RemoveUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            List<string> roleUser = (List<string>)await _userManager.GetRolesAsync(user);
            List<string> roleID = new List<string>();
            foreach (var role in roleUser)
            {
                roleID.Add(_roleManager.Roles.FirstOrDefault(r => r.Name == role).Id.ToString());
            }
            if (user != null)
            {
                // remove automate role`s user
                IdentityResult result = await _userManager.DeleteAsync(user);

                if (result.Succeeded)
                    return RedirectToAction("ListUser");
                else
                    return BadRequest();
            }
            else
                return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var userInfo = new UserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName
            };

            return View(userInfo);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(UserViewModel user)
        {
            var userInfo = await _userManager.FindByIdAsync(user.Id);
            if (userInfo != null)
            {
                if (!string.IsNullOrEmpty(userInfo.Email))
                    userInfo.Email = user.Email;
                else
                    ModelState.AddModelError("", "Email cannot be empty");

                if (!string.IsNullOrEmpty(userInfo.UserName))
                    userInfo.UserName = user.UserName;
                else
                    ModelState.AddModelError("", "UserName cannot be empty");


                if (!string.IsNullOrEmpty(userInfo.PasswordHash))
                    userInfo.PasswordHash = _passwordHasher.HashPassword(userInfo, user.Password);
                else
                    ModelState.AddModelError("", "Password cannot be empty");

                if (!string.IsNullOrEmpty(userInfo.Email) && !string.IsNullOrEmpty(userInfo.PasswordHash))
                {
                    IdentityResult result = await _userManager.UpdateAsync(userInfo);
                    if (result.Succeeded)
                        return RedirectToAction("ListUser");
                    else
                        return BadRequest();
                }
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> DetailUser(string id)
        {
            if(!string.IsNullOrEmpty(id))
            {
                var user = await _userManager.FindByIdAsync(id);

                var userInfo = new UserViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    UserName = user.UserName,
                    ProfilePicture = user.ProfilePictureUser,
                    PhoneNumber = user.PhoneNumber,
                    EmailConfirmed = user.EmailConfirmed,
                    PhoneNumberConfirmed = user.PhoneNumberConfirmed,
                    TwoFactorEnabled = user.TwoFactorEnabled,
                    Roles = await _userManager.GetRolesAsync(user)
                };
                return View(userInfo);
            }
            
            return View();
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddUser(UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                var userInfo = new ApplicationUser()
                {
                    UserName = user.UserName,
                    Email = user.Email
                };

                await _userManager.CreateAsync(userInfo, user.Password);
                await _userManager.AddToRoleAsync(userInfo, user.Role); 
                return RedirectToAction("ListUser");
            }
            else
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                ModelState.AddModelError(nameof(allErrors), allErrors.ToString());
            }
            return View(user);
        }
    }
}

OnionArcitectureProject.Web/Areas/Admin/Views/Setting/AddUser.cshtml
@using OnionArcitectureProject.Entities
@using Microsoft.EntityFrameworkCore
@model OnionArcitectureProject.ViewModels.UserViewModel


<h1>New user</h1>

<form method="post">
    <div class="text-danger" style="direction:rtl" asp-validation-summary="All"></div>

    <div class="form-group">
        <label asp-for="@Model.Email"></label>
        <input asp-for="@Model.Email" class="form-control" />
        <span asp-validation-for="@Model.Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.UserName"></label>
        <input asp-for="@Model.UserName" class="form-control" />
        <span asp-validation-for="@Model.UserName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Password"></label>
        <input asp-for="@Model.Password" class="form-control" />
        <span asp-validation-for="@Model.Password" class="text-danger"></span>
    </div>


    <div class="form-group">
        <label asp-for="@Model.Role"></label>

        <select asp-for="@Model.Role" aria-selected="True">
            @foreach (var role in Enum.GetNames(typeof(Roles)))
            {
                <option value="@role" selected>@role</option>
            }
        </select>

        <span asp-validation-for="@Model.Role" class="text-danger"></span>
    </div>

    <input type="submit" />
</form>

@section Scripts{
<partial name="_ValidationScriptsPartial" />

}

OnionArcitectureProject.Web/Areas/Admin/Views/Setting/DetailUser.cshtml
@model OnionArcitectureProject.ViewModels.UserViewModel

<h1>User detail</h1>

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="@Model.ProfilePicture" alt="Card image cap">
  <div class="card-body">
    <h3 class="card-title">@Model.UserName</h3>

    <span>
        <p>Email</p>
    </span>
    
    <a class="btn btn-primary" asp-action="ListUser">Back</a>
  </div>
</div>

<div class="row">
    <div clss="col-1">
        <h4>User name: </h4>
    </div>
    <div class="col-1">
        <h4>@Model.UserName</h4>
    </div>
</div>

<div class="row">
    <div clss="col-1">
        <h4>پست الکترونیک: </h4>
    </div>
    <div class="col-1">
        <h4>@Model.Email</h4>
    </div>
</div>

<div class="row">
    <div clss="col-1">
        <h4>نقش کاربری: </h4>
    </div>
    <div class="col-1">
        @foreach (var role in Model.Roles)
        {
            <h4>@role.ToString()</h4>
        }

    </div>


    <a class="btn btn-primary" asp-action="ListUser">برگشت</a>

</div>

OnionArcitectureProject.Web/Areas/Admin/Views/Setting/ListUser.cshtml
@model List<OnionArcitectureProject.ViewModels.UserViewModel>

<a class="btn btn-primary" asp-controller="Setting" asp-action="AddUser">New user</a>
<br />
<br />
<table class="table" dir="ltr">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">User name</th>
            <th scope="col">Email</th>
            <th scope="col">Role</th>
            <th scope="col">Command</th>

        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var user in Model)
        {
            <tr>
                <th scope="row">
                    @i
                </th>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>
                    @foreach (var role in user.Roles)
                    {
                        <span>@role |</span>
                    }
                </td>
                <td>
                    <a class="mx-2">
                        <i class="far fa-trash-alt" style="font-size:1.5rem" data-toggle="modal" data-target="#exampleModalCenter"></i>
                    </a> |

                    <a asp-action="EditUser" asp-route-id="@user.Id"
                   class="mx-2">
                        <i class="far fa-edit" style="font-size:1.5rem"></i>
                    </a> |

                    <a asp-action="DetailUser" asp-route-id="@user.Id"
                   class="mx-2">
                        <i class="fas fa-info-circle" style="font-size:1.5rem"></i>
                    </a>
                </td>
            </tr>

            i++;

            <!-- Modal -->
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Warning</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure want delete this user?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <a asp-action="RemoveUser" asp-route-id="@user.Id" type="button" class="btn btn-danger">Delete user</a>
                        </div>
                    </div>
                </div>
            </div>


        }
    </tbody>
</table>






@section Scripts
{
<script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>

<!-- SweetAlert2 -->
<script src="~/Admin/plugins/sweetalert2/sweetalert2.min.js"></script>

<!-- Toastr -->
<script src="~/Admin/plugins/toastr/toastr.min.js"></script>


}

@section CssFiles
{
<!-- SweetAlert2 -->
<link rel="stylesheet" href="~/Admin/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css" />

<!-- Toastr -->
<link rel="stylesheet" href="~/Admin/plugins/toastr/toastr.min.css" />
}